# Generated by Django 5.1.1 on 2024-09-15 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versionRef', models.IntegerField(verbose_name='Version Ref')),
                ('quarterRef', models.IntegerField(verbose_name='Quarter Ref')),
                ('reportingDate', models.DateField(verbose_name='Reporting Date')),
                ('dueDate', models.DateField(verbose_name='Due Date')),
                ('firstSubmittedDatetime', models.DateTimeField(verbose_name='First Submitted Datetime')),
                ('lastSubmittedDatetime', models.DateTimeField(verbose_name='Last Submitted Datetime')),
            ],
        ),
        migrations.CreateModel(
            name='CreditRiskDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DepositsInvestmentsDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FirmDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoanCategoryDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LoanMaturityDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StateDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StatusDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSheetFact',
            fields=[
                ('returnId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.scheduledfact', verbose_name='Return Id')),
                ('cashBalancesBank', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cash Balances at Bank')),
                ('depositsInvestmentsCashEquivalents', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Deposits and Investments: Cash Equivalents')),
                ('depositsInvestmentsOther', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Deposits and Investments: Other')),
                ('membersLoans', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Members Loans')),
                ('badDebtProvisions', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bad Debt Provisions')),
                ('tangibleFixedAssets', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tangible Fixed Assets')),
                ('debtorsPrepayments', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Debtors and Prepayments')),
                ('totalAssets', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Assets')),
                ('membersShares', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Members Shares')),
                ('membersBudgetAccounts', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Members Budget Accounts')),
                ('liabilitiesAccruals', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Liabilities and Accruals')),
                ('otherProvisions', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Other Provisions')),
                ('totalLiabilities', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Liabilities')),
                ('regulatoryReserve', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Regulatory Reserve')),
                ('operationalRiskReserve', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Operational Risk Reserve')),
                ('surplusOrDeficit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Surplus or Deficit BS')),
                ('otherRealisedReserves', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Other Realised Reserves')),
                ('otherUnrealisedReserves', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Other Unrealised Reserves')),
                ('totalReserves', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Reserves')),
                ('totalLiabilitiesReserves', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Liabilities and Reserves')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeExpenditureFact',
            fields=[
                ('returnId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.scheduledfact', verbose_name='Return Id')),
                ('memberLoanInterest', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Member Loan Interest')),
                ('otherInterestIncome', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Other Interest Income')),
                ('otherIncome', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Other Income')),
                ('totalIncome', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Income')),
                ('employmentCosts', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Employment Costs')),
                ('otherManagementCosts', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Other Management Costs')),
                ('depreciationCosts', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Depreciation Costs')),
                ('netMemberLoanImpairment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Member Loan Impairment')),
                ('totalExpenditure', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Expenditure')),
                ('surplusOrDeficit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Surplus Or Deficit IEA')),
            ],
        ),
        migrations.CreateModel(
            name='CreditRiskFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberCreditRisk', models.IntegerField(verbose_name='Number of Loans by Credit Risk')),
                ('amountCreditRisk', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount of Loans by Credit Risk')),
                ('provisionsAmountCreditRisk', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount of Provisions by Credit Risk')),
                ('creditRiskDim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.creditriskdim', verbose_name='Credit Risk Id')),
                ('returnId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.scheduledfact', verbose_name='Return Id')),
            ],
        ),
        migrations.CreateModel(
            name='DepositsInvestmentsFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountsAuthorisedCreditInstitutions', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Accounts in Authorised Credit Institutions by Maturity')),
                ('irishEeaStateSecurities', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Irish and EEA State Securities by Maturity')),
                ('centralBankDeposits', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Central Bank Deposits by Maturity')),
                ('bankBonds', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bank Bonds by Maturity')),
                ('otherInvestments', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Other Investments by Maturity')),
                ('totalDepositsAndInvestments', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Deposits and Investments by Maturity')),
                ('depositsInvestmentsDim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.depositsinvestmentsdim', verbose_name='Deposits and Investments Maturity Id')),
                ('returnId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.scheduledfact', verbose_name='Return Id')),
            ],
        ),
        migrations.AddField(
            model_name='scheduledfact',
            name='firmId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.firmdim', verbose_name='Firm Id'),
        ),
        migrations.CreateModel(
            name='AdvancedLoanCategoryFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberAdvancedCategory', models.IntegerField(verbose_name='Number of Advanced Loans by Category')),
                ('amountAdvancedCategory', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount of Advanced Loans by Category')),
                ('returnId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.scheduledfact', verbose_name='Return Id')),
                ('loanCategoryDim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.loancategorydim', verbose_name='Loan Category Id')),
            ],
        ),
        migrations.CreateModel(
            name='AdvancedLoanMaturityFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberAdvancedMaturity', models.IntegerField(verbose_name='Number of Advanced Loans by Maturity')),
                ('amountAdvancedMaturity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount of Advanced Loans by Maturity')),
                ('returnId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.scheduledfact', verbose_name='Return Id')),
                ('loanMaturityDim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.loanmaturitydim', verbose_name='Loan Maturity Id')),
            ],
        ),
        migrations.CreateModel(
            name='OutstandingLoanCategoryFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOutstandingCategory', models.IntegerField(verbose_name='Number of Outstanding Loans by Category')),
                ('amountOutstandingCategory', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount of Outstanding Loans by Category')),
                ('loanCategoryDim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.loancategorydim', verbose_name='Loan Category Id')),
                ('returnId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.scheduledfact', verbose_name='Return Id')),
            ],
        ),
        migrations.CreateModel(
            name='OutstandingLoanMaturityFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOutstandingMaturity', models.IntegerField(verbose_name='Number of Outstanding Loans by Maturity')),
                ('amountOutstandingMaturity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount of Outstanding Loans by Maturity')),
                ('loanMaturityDim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.loanmaturitydim', verbose_name='Loan Maturity Id')),
                ('returnId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.scheduledfact', verbose_name='Return Id')),
            ],
        ),
        migrations.AddField(
            model_name='scheduledfact',
            name='stateId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.statedim', verbose_name='State Id'),
        ),
        migrations.AddField(
            model_name='scheduledfact',
            name='statusId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.statusdim', verbose_name='Status Id'),
        ),
        migrations.AddField(
            model_name='scheduledfact',
            name='templateId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.templatedim', verbose_name='Template Id'),
        ),
    ]
