# Generated by Django 5.1.1 on 2024-09-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledfact',
            old_name='firmId',
            new_name='firm',
        ),
        migrations.RenameField(
            model_name='scheduledfact',
            old_name='stateId',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='scheduledfact',
            old_name='statusId',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='scheduledfact',
            old_name='templateId',
            new_name='template',
        ),
    ]
