# Generated by Django 5.1.1 on 2024-09-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_firmid_scheduledfact_firm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedloancategoryfact',
            name='amountAdvancedCategory',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount of Advanced Loans by Category'),
        ),
        migrations.AlterField(
            model_name='advancedloanmaturityfact',
            name='amountAdvancedMaturity',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount of Advanced Loans by Maturity'),
        ),
        migrations.AlterField(
            model_name='balancesheetfact',
            name='badDebtProvisions',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Bad Debt Provisions'),
        ),
        migrations.AlterField(
            model_name='balancesheetfact',
            name='cashBalancesBank',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cash Balances at Bank'),
        ),
        migrations.AlterField(
            model_name='balancesheetfact',
            name='debtorsPrepayments',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Debtors and Prepayments'),
        ),
        migrations.AlterField(
            model_name='balancesheetfact',
            name='depositsInvestmentsCashEquivalents',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Deposits and Investments: Cash Equivalents'),
        ),
        migrations.AlterField(
            model_name='balancesheetfact',
            name='depositsInvestmentsOther',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Deposits and Investments: Other'),
        ),
        migrations.AlterField(
            model_name='balancesheetfact',
            name='liabilitiesAccruals',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Liabilities and Accruals'),
        ),
        migrations.AlterField(
            model_name='balancesheetfact',
            name='membersBudgetAccounts',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Members Budget Accounts'),
        ),
        migrations.AlterField(
            model_name='balancesheetfact',
            name='membersLoans',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Members Loans'),
        ),
        migrations.AlterField(
            model_name='balancesheetfact',
            name='membersShares',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Members Shares'),
        ),
        migrations.AlterField(
            model_name='balancesheetfact',
            name='operationalRiskReserve',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Operational Risk Reserve'),
        ),
        migrations.AlterField(
            model_name='balancesheetfact',
            name='otherProvisions',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Other Provisions'),
        ),
        migrations.AlterField(
            model_name='balancesheetfact',
            name='otherRealisedReserves',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Other Realised Reserves'),
        ),
        migrations.AlterField(
            model_name='balancesheetfact',
            name='otherUnrealisedReserves',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Other Unrealised Reserves'),
        ),
        migrations.AlterField(
            model_name='balancesheetfact',
            name='regulatoryReserve',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Regulatory Reserve'),
        ),
        migrations.AlterField(
            model_name='balancesheetfact',
            name='surplusOrDeficit',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Surplus or Deficit BS'),
        ),
        migrations.AlterField(
            model_name='balancesheetfact',
            name='tangibleFixedAssets',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tangible Fixed Assets'),
        ),
        migrations.AlterField(
            model_name='balancesheetfact',
            name='totalAssets',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Assets'),
        ),
        migrations.AlterField(
            model_name='balancesheetfact',
            name='totalLiabilities',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Liabilities'),
        ),
        migrations.AlterField(
            model_name='balancesheetfact',
            name='totalLiabilitiesReserves',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Liabilities and Reserves'),
        ),
        migrations.AlterField(
            model_name='balancesheetfact',
            name='totalReserves',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Reserves'),
        ),
        migrations.AlterField(
            model_name='creditriskfact',
            name='amountCreditRisk',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount of Loans by Credit Risk'),
        ),
        migrations.AlterField(
            model_name='creditriskfact',
            name='provisionsAmountCreditRisk',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount of Provisions by Credit Risk'),
        ),
        migrations.AlterField(
            model_name='depositsinvestmentsfact',
            name='accountsAuthorisedCreditInstitutions',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Accounts in Authorised Credit Institutions by Maturity'),
        ),
        migrations.AlterField(
            model_name='depositsinvestmentsfact',
            name='bankBonds',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Bank Bonds by Maturity'),
        ),
        migrations.AlterField(
            model_name='depositsinvestmentsfact',
            name='centralBankDeposits',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Central Bank Deposits by Maturity'),
        ),
        migrations.AlterField(
            model_name='depositsinvestmentsfact',
            name='irishEeaStateSecurities',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Irish and EEA State Securities by Maturity'),
        ),
        migrations.AlterField(
            model_name='depositsinvestmentsfact',
            name='otherInvestments',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Other Investments by Maturity'),
        ),
        migrations.AlterField(
            model_name='depositsinvestmentsfact',
            name='totalDepositsAndInvestments',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Deposits and Investments by Maturity'),
        ),
        migrations.AlterField(
            model_name='incomeexpenditurefact',
            name='depreciationCosts',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Depreciation Costs'),
        ),
        migrations.AlterField(
            model_name='incomeexpenditurefact',
            name='employmentCosts',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Employment Costs'),
        ),
        migrations.AlterField(
            model_name='incomeexpenditurefact',
            name='memberLoanInterest',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Member Loan Interest'),
        ),
        migrations.AlterField(
            model_name='incomeexpenditurefact',
            name='netMemberLoanImpairment',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Net Member Loan Impairment'),
        ),
        migrations.AlterField(
            model_name='incomeexpenditurefact',
            name='otherIncome',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Other Income'),
        ),
        migrations.AlterField(
            model_name='incomeexpenditurefact',
            name='otherInterestIncome',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Other Interest Income'),
        ),
        migrations.AlterField(
            model_name='incomeexpenditurefact',
            name='otherManagementCosts',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Other Management Costs'),
        ),
        migrations.AlterField(
            model_name='incomeexpenditurefact',
            name='surplusOrDeficit',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Surplus Or Deficit IEA'),
        ),
        migrations.AlterField(
            model_name='incomeexpenditurefact',
            name='totalExpenditure',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Expenditure'),
        ),
        migrations.AlterField(
            model_name='incomeexpenditurefact',
            name='totalIncome',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Income'),
        ),
        migrations.AlterField(
            model_name='outstandingloancategoryfact',
            name='amountOutstandingCategory',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount of Outstanding Loans by Category'),
        ),
        migrations.AlterField(
            model_name='outstandingloanmaturityfact',
            name='amountOutstandingMaturity',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount of Outstanding Loans by Maturity'),
        ),
    ]
