# Generated by Django 5.1.1 on 2024-09-27 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0003_alter_advancedloancategoryfact_amountadvancedcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalKeyMeasure',
            fields=[
                ('returnId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.scheduledfact', verbose_name='Return Id')),
                ('totalAssets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Assets')),
                ('surplusOrDeficit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Surplus Or Deficit')),
                ('regulatoryReserve', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Regulatory Reserve')),
                ('totalRealisedReserves', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Realised Reserves')),
                ('totalMemberSavings', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Member Savings')),
                ('regulatoryReserveRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Regulatory Reserve Ratio (TA)')),
                ('totalRealisedReservesRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Realised Reserves Ratio (TA)')),
                ('tangibleFixedAssetsTaRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Tangible Fixed Assets Ratio (TA)')),
                ('tangibleFixedAssetsTrrRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Tangible Fixed Assets Ratio (TRR)')),
                ('returnOnAssetsRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Return On Assets Ratio (TA)')),
                ('costToIncomeRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cost To Income Ratio (TI)')),
            ],
        ),
    ]
