# Generated by Django 5.1.1 on 2024-09-27 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_advancedloancategoryfact_amountadvancedcategory_and_more'),
        ('key_measures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityKeyMeasure',
            fields=[
                ('returnId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.scheduledfact', verbose_name='Return Id')),
                ('liquidityRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Liquidity Ratio')),
                ('shortTermLiquidityRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Short Term Liquidity Ratio')),
            ],
        ),
    ]
