# Generated by Django 5.1.1 on 2024-09-27 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_advancedloancategoryfact_amountadvancedcategory_and_more'),
        ('key_measures', '0002_liquiditykeymeasure'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentKeyMeasure',
            fields=[
                ('returnId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.scheduledfact', verbose_name='Return Id')),
                ('totalInvestments', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Investments')),
                ('investmentsToAssetsRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Investments to Assets Ratio')),
                ('aaciToInvestmentsRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='AACI to Investments Ratio')),
                ('ieeassToInvestmentsRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='IEEASS to Investments Ratio')),
                ('centralBankDepositsToInvestmentsRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='CBD to Investments Ratio')),
                ('bankBondsToInvestmentsRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Bank Bonds to Investments Ratio')),
                ('otherInvestmentsToInvestmentsRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Other Investments to Investments Ratio')),
                ('investmentsOver5YearsRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Investments Over 5 Years Ratio')),
                ('investmentsOver7YearsRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Investments Over 7 Years Ratio')),
                ('investmentsOver10YearsRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Investments Over 10 Years Ratio')),
                ('returnOnInvestmentsRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Return on Investments')),
            ],
        ),
    ]
