# Generated by Django 5.1.1 on 2024-09-28 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_advancedloancategoryfact_amountadvancedcategory_and_more'),
        ('key_measures', '0003_investmentkeymeasure'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditKeyMeasure',
            fields=[
                ('returnId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.scheduledfact', verbose_name='Return Id')),
                ('totalLoans', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Loans')),
                ('totalProvisions', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Provisions')),
                ('arrearsOver9Weeks', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Arrears Over 9 Weeks')),
                ('loanToAssetsRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Loans to Assets Ratio')),
                ('arrearsOver9WeeksRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Arrears Over 9 Weeks Ratio')),
                ('personalLoansRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Personal Loans Ratio')),
                ('houseLoansRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='House Loans Ratio')),
                ('commercialLoansRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Commercial Loans Ratio')),
                ('communityLoansRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Community Loans Ratio')),
                ('otherLoansRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Other Loans Ratio')),
                ('advancedPersonalLoansRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Advanced Personal Loans Ratio')),
                ('advancedHouseLoansRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Advanced House Loans Ratio')),
                ('advancedCommercialLoansRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Advanced Commercial Loans Ratio')),
                ('advancedCommunityLoansRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Advanced Community Loans Ratio')),
                ('advancedOtherLoansRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Advanced Other Loans Ratio')),
                ('loansOver5YearsRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Loans Over 5 Years Ratio')),
                ('loansOver10YearsRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Loans Over 10 Years Ratio')),
                ('advancedLoansOver5YearsRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Advanced Loans Over 5 Years Ratio')),
                ('advancedLoansOver10YearsRatio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Advanced Loans Over 10 Years Ratio')),
            ],
        ),
    ]
