# Generated by Django 5.1.1 on 2024-09-29 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0003_alter_advancedloancategoryfact_amountadvancedcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRReview',
            fields=[
                ('pr_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50, verbose_name='Source')),
                ('measure', models.CharField(max_length=150, verbose_name='Measure')),
                ('current_Q0', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prior_Q1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prior_Q2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prior_Q3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prior_Q4', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('perc_diff_pq', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('perc_diff_py', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('average', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('returnId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.scheduledfact', verbose_name='Return Id')),
            ],
            options={
                'verbose_name': 'PR Review',
                'verbose_name_plural': 'PR Reviews',
            },
        ),
    ]
