# Generated by Django 5.1.1 on 2024-09-29 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0003_alter_advancedloancategoryfact_amountadvancedcategory_and_more'),
        ('pr_reviews', '0002_delete_prreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRReviewTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('returnId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr_reviews', to='data.scheduledfact')),
            ],
        ),
        migrations.CreateModel(
            name='PRReviewMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('measure', models.CharField(max_length=100)),
                ('current_Q0', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prior_Q1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prior_Q2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prior_Q3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prior_Q4', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('perc_diff_pq', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('perc_diff_py', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('average', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('pr_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='pr_reviews.prreviewtable')),
            ],
        ),
    ]
