# Generated by Django 5.1.1 on 2024-10-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_reviews', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prreviewtable',
            name='capital_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prreviewtable',
            name='credit_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prreviewtable',
            name='final_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prreviewtable',
            name='investments_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prreviewtable',
            name='liquidity_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
