# Generated by Django 5.1.1 on 2024-10-10 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_reviews', '0004_prreviewtable_capital_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prreviewtable',
            name='senior_supervisor_so_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prreviewtable',
            name='senior_supervisor_so_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senior_supervisor_signoffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prreviewtable',
            name='supervisor_so_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prreviewtable',
            name='supervisor_so_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_signoffs', to=settings.AUTH_USER_MODEL),
        ),
    ]
